master:
  useSecurity: true
  adminUser: admin
  adminPassword: password
  numExecutors: 1
  installPlugins:
    - kubernetes:1.26.4
    - workflow-job:2.39
    - workflow-aggregator:2.6
    - credentials-binding:1.23
    - git:4.3.0
    - command-launcher:1.4
    - github-branch-source:2.8.3
    - docker-workflow:1.23
    - pipeline-utility-steps:2.6.1
  overwritePlugins: true
  serviceType: NodePort
